# Generated by Django 5.0.6 on 2024-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_alter_letter_letter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
