# Generated by Django 5.0.6 on 2024-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_letter_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
