# Generated by Django 5.0.6 on 2024-07-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=200, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('s', 'سهامی خاص'), ('g', 'سهامی عام')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=800)),
                ('site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('s', 'سهامدار'), ('c', 'مشتری'), ('e', 'کارمند')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('national_code', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=200, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/image/')),
                ('date_birth', models.DateTimeField(blank=True, null=True)),
                ('personel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PositionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
    ]
